### ISSUE TITLE
[CPU Power Management] Strange frequency behaviour after sleep/wake

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1086]
Hi there,
today I've noticed a frustrating behaviour on my Dell Inspiron 5370:

when I resume from a sleep/wake cycle, sometimes the CPU maximum frequency lowers to 600/800MHz, resulting with stuttering and unusability of the system. Below a few screenshot I took a few minutes ago:

![image](https://user-images.githubusercontent.com/17933708/89706565-30189e00-d967-11ea-8fba-8096c0c09746.png)

![image](https://user-images.githubusercontent.com/17933708/89706567-36a71580-d967-11ea-969a-80e232dae504.png)

I'm using the latest prebuilt version of OpenCore (0.6.0) and the latest versions of the kexts. You can find my EFI folder [here](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh).

I did a BIOS update a few days ago, but I don't think that this can interfere in some strange-way with this issue. The CFG Lock is disabled, since I can boot without AppleCpuPmCfgLock and AppleXcpmCfgLock quirks.
If you need AppleIntelInfo.kext output please let me know

Hope that this issue can be fixed
Have a nice day

**Comment by Mateo1234454545** [comment]
You get it wrong.
Gpu freq is the problem. It hangs at max speed and for the temps to not go up , cpu stays low.

This happens to me also, with latest kext and opencore on Big Sur.

**Comment by vit9696** [comment]
I believe you need custom XCPM vector configuration to resolve this issue. Out of the scope of the bugtracker.

**Comment by Mateo1234454545** [comment]
@dreamwhite , try with this kext and report back.
[WhateverGreen.kext.zip](https://github.com/acidanthera/bugtracker/files/5074202/WhateverGreen.kext.zip)

**Comment by kadaluarsa** [comment]
@Mateo1234454545 @dreamwhite is it solved ? im using OC 0.6.0 latest kext but still got low freq after wake from sleep mode.

**Comment by dreamwhite** [comment]
Hi @Mateo1234454545, sorry if I didn't reported back but I was on holiday and returned tonight. I've tried sleeping/waking many times and it seems that the CPU frequency is fine (I'm not experiencing any type of lag or whatelse). 
I think that the problem is solved :)

**Comment by asgmeonerandom** [comment]
> @dreamwhite , try with this kext and report back.
> [WhateverGreen.kext.zip](https://github.com/acidanthera/bugtracker/files/5074202/WhateverGreen.kext.zip)

what did you change in the code?

**Comment by Mateo1234454545** [comment]
Nothing.
Just compiled the kext without the latest commits.

**Comment by Mateo1234454545** [comment]
> @Mateo1234454545 @dreamwhite is it solved ? im using OC 0.6.0 latest kext but still got low freq after wake from sleep mode.
> 
> edit : i think its solved now im using kext from @Mateo1234454545 and cpu freq back to normal



> Hi @Mateo1234454545, sorry if I didn't reported back but I was on holiday and returned tonight. I've tried sleeping/waking many times and it seems that the CPU frequency is fine (I'm not experiencing any type of lag or whatelse).
> I think that the problem is solved :)

Problem still exists , with 2 differences : 

a) It doen't happen as  often as before. In fact It happened only 1 time  after 3days of having awaking laptop from sleep over 30times.
b) GPU hangs at 0,3gzh and not at max frequency.

**Comment by kadaluarsa** [comment]
c) TurboFrequency disabled after wake from sleep mode.
