### ISSUE TITLE
[WhateverGreen] SSDT-PNLF clarifications

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1317]
Hi there,
I was analyzing [SSDT-PNLF](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl) and  I've noticed that after compiling the SSDT into AML, the following warning appeared:

`97, 3115, Not all control paths return a value (\_SB.PCI0.GFX0.PNLF._INI)`

According to Advanced Configuration and Power Interface Specification version 6.3, page [471](https://uefi.org/sites/default/files/resources/ACPI_6_3_May16.pdf#page=523):

- `_INI` methods mustn't return any type of value

At this point, line [119](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl#L119) of SSDT-PNLF goes against ACPI specification.

Is this "error" even wanted?

Another thing that made me doubt is the use of `_HID` and `_ADR` variables. 
According to iasl compiler, we should use only one of them. Is this "error" even wanted? 

Thank you so much for your effort and have a great weekend :")

**Comment by Andrey1970AppleLife** [comment]
> `97, 3115, Not all control paths return a value (\_SB.PCI0.GFX0.PNLF._INI)`

No this warning with the last stable version iasl 20200925.

> `Another thing that made me doubt is the use of _HID and _ADR variables.`

Fixed in master.

**Comment by dreamwhite** [comment]
> No this warning with the last stable version iasl 20200925.

Alright, so we can ignore this error right? 



> Fixed in master.

Okay, thank you so much :")

**Comment by Andrey1970AppleLife** [comment]
> Alright, so we can ignore this error right?

If you see an error or warning on it, you need to update iasl.

**Comment by dreamwhite** [comment]
> > Alright, so we can ignore this error right?
> 
> If you see an error or warning on it, you need to update iasl.

I've updated iASL from MaciASL preferences but still see that damn error :/ 

![image](https://user-images.githubusercontent.com/17933708/99879099-b69d7680-2c0a-11eb-94ba-e5395cb0641c.png)

![image](https://user-images.githubusercontent.com/17933708/99879102-be5d1b00-2c0a-11eb-912e-ec164df9b189.png)

My question is: what does [Line 119](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl#L119) exactly do?

**Comment by Andrey1970AppleLife** [comment]
Strange

![Снимок экрана 2020-11-21 в 17 08 53](https://user-images.githubusercontent.com/17758753/99879207-50b9ea80-2c1c-11eb-983e-62bf8c67e6a5.png)
![Снимок экрана 2020-11-21 в 17 08 34](https://user-images.githubusercontent.com/17758753/99879210-54e60800-2c1c-11eb-94c8-dadaf37dbeae.png)

**Comment by dreamwhite** [comment]
> Strange
> 
> ![Снимок экрана 2020-11-21 в 17 08 53](https://user-images.githubusercontent.com/17758753/99879207-50b9ea80-2c1c-11eb-983e-62bf8c67e6a5.png)
> ![Снимок экрана 2020-11-21 в 17 08 34](https://user-images.githubusercontent.com/17758753/99879210-54e60800-2c1c-11eb-94c8-dadaf37dbeae.png)

Wait, I'm noticing that you're compiling SSDT-PNLF.dsl.

In order to reproduce the warning you have to:

1. save SSDT-PNLF.dsl into .aml
2. close MaciASL and open SSDT-PNLF.aml
3. Compile again the SSDT and you'll get the warning.

That doesn't make much sense tbh 😂

**Comment by Andrey1970AppleLife** [comment]
Yes, so there is a warning.
СС @vit9696, @Moorre

**Comment by vit9696** [comment]
The decompiler may not always be able to recover the original code. You should report this to github.com/acpica if you want it to be fixed.

**Comment by stevezhengshiqi** [comment]
Yeah, the iasl decompiler sometimes behaves wired.
But in this case, the original code of SSDT-PNLF seems against ACPI specification. I agree with @dreamwhite that [L119](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/SSDT-PNLF.dsl#L119) violates ACPI Specification that
`_INI methods mustn't return any type of value`. Maybe we need a workaround here.

**Comment by vit9696** [comment]
The original code does not return any value, and L119 has `Return` not `Return SOMETHING`, thus the code is correct.

**Comment by foskvs** [comment]
Line 119 returns Zero if (Local4&1) == 0

```acpiexec SSDT-PNLF.aml
acpi_sem_0
acpi_sem_1
acpi_sem_2
acpi_sem_3
acpi_sem_4
acpi_sem_5
acpi_sem_6
acpi_sem_7
acpi_sem_8
acpi_sem_9
acpi_sem_10
acpi_sem_11
acpi_sem_12
acpi_sem_13
acpi_sem_14
acpi_sem_15
acpi_sem_16

Intel ACPI Component Architecture
AML Execution/Debug Utility version 20201113
Copyright (c) 2000 - 2020 Intel Corporation

Input file SSDT-PNLF.aml, Length 0x475 (1141) bytes


ACPI: RSDP 0x0000000106C57000 000024 (v02 Intel )
ACPI: XSDT 0x00007F90D5406060 00003C (v00 Intel  AcpiExec 00001001 INTL 20201113)
ACPI: FACP 0x0000000106C56EA0 000114 (v05 Intel  AcpiExec 00001001 INTL 20201113)
ACPI: DSDT 0x0000000106C55620 000024 (v02 Intel  Local    00000001 INTL 20090730)
ACPI: FACS 0x0000000106C57028 000040
ACPI: SSDT 0x00007F90D580E800 000475 (v02                 00000000 INTL 20201113)

ACPI table initialization:
Table [DSDT: Local   ] (id 01) -    0 Objects with   0 Devices,   0 Regions,    0 Methods (0/0/0 Serial/Non/Cvt)
Table [SSDT:         ] (id 02) -   23 Objects with   3 Devices,   2 Regions,    2 Methods (0/2/0 Serial/Non/Cvt)
ACPI: 2 ACPI AML tables successfully acquired and loaded

Final data object initialization: Namespace contains 32 (0x20) objects
Initializing General Purpose Events (GPEs):
    Initialized GPE 00 to 7F [_GPE] 16 regs on interrupt 0x0 (SCI)
    Initialized GPE 80 to FF [_GPE] 16 regs on interrupt 0x0 (SCI)
Initializing Device/Processor/Thermal objects and executing _INI/_STA methods:
    Executed 1 _INI methods requiring 1 _STA executions (examined 5 objects)
- evaluate  \_SB.PCI0.GFX0.PNLF._INI
Evaluating \_SB.PCI0.GFX0.PNLF._INI
Evaluation of \_SB.PCI0.GFX0.PNLF._INI returned object 0x7f90d5809800, external buffer length 18
  [Integer] = 0000000000000000
```

**Comment by vit9696** [comment]
Like I said, this is a bug in iasl no matter how you look at it, and this is one of the reasons we call this iasl _testing_ instead of stable. Filed in https://github.com/acpica/acpica/issues/653.

**Comment by 5T33Z0** [comment]
I am wondering why the `SSDT-PNLF` sample still contains external references to `RMCF`. It's referncing parameters which are defined in `SSDT-RMCF.aml` (Rehabman Configuration File), which can be used to change/adjust certain parameters in other SSDTs of his Laptop hotpatch compendium. But since no one uses `SSDT-RCMF` anymore, these external references don't exist. So wouldn't it be a cleaner to re-write SSDT-PNLF without these non-existing external references?
