### ISSUE TITLE
Always stuck in ExitBS:Start for Lenovo Thinkpad X1 Extreme Gen 3

### ISSUE THREAD

**Issue by andreszerocross** [acidanthera/bugtracker#1486]
Notebook Specifications :
Processor : Intel Core i7 10850H
GPU : Intel HD Graphics 10Th Gen + Nvidia GTX 1650Ti

MAT support is 1

I have set 

Combination
- AvoidRuntimeDefrag, DevirtualiseMmio, EnableSafeModeSlide, RebuildAppleMemoryMap and SyncRuntimePermissions = YES

Result : ExitBS:Start
(Log from this combination is attached)
[RebuildAppleMap + SyncRuntimePermission.txt](https://github.com/acidanthera/bugtracker/files/5950881/RebuildAppleMap.%2B.SyncRuntimePermission.txt)

Other Combination
- AvoidRuntimeDefrag, EnableSafeModeSlide, EnableWriteUnprotector, SetupVirtualMap = YES

Result : ExitBS:Start
(Log from this combination is attached)
[EnableWriteUnpretctor + Setup VirtualMap.txt](https://github.com/acidanthera/bugtracker/files/5950878/EnableWriteUnpretctor.%2B.Setup.VirtualMap.txt)

I have checked debug log with OpenCore Debug version and there is no MMIO Region, so MMIO Whitelist like other Icelake notebook can't be set,

Thank you very much

**Comment by dreamwhite** [comment]
First of all, have you tried enabling `ProtectUefiServices`? 
I had a discussion with @vit9696 a few weeks ago where he explained that this quirk is needed if you don't see any MMIO region inside the Logs ._."

Since you have a 10th gen CPU and MAT Support is 1, you'll have to set the booter quirks as it follows:

![image](https://user-images.githubusercontent.com/17933708/107357165-008f4d80-6ad2-11eb-8890-ea9930da2403.png)

**Comment by andreszerocross** [comment]
Sorry,, i have set this too, You can see in the log 
![image](https://user-images.githubusercontent.com/9614101/107358067-824c9e80-6b05-11eb-9acc-c83c64ac237f.png)

But result is same

**Comment by dreamwhite** [comment]
> Sorry,, i have set this too, You can see in the log
> ![image](https://user-images.githubusercontent.com/9614101/107360895-23892400-6b09-11eb-87e3-2a5125e66545.png)
> 
> But result is same

Since your CFG Lock is 1, have you enabled CFG Lock patches?

**Comment by andreszerocross** [comment]
> > Sorry,, i have set this too, You can see in the log
> > ![image](https://user-images.githubusercontent.com/9614101/107360895-23892400-6b09-11eb-87e3-2a5125e66545.png)
> > But result is same
> 
> Since your CFG Lock is 1, have you enabled CFG Lock patches?

Yes, i have set this to enable, Because i can't set this to disable in BIOS (like other gigabyte motherboard).

But result is same, AppleXcpmCfgLock patch is success if you see the debug log

**Comment by vit9696** [comment]
There currently are two somewhat similar boards. Basically the requirement is to find the place it dies through either kernel patches or OpenCore patches.
https://github.com/acidanthera/bugtracker/issues/1354
https://github.com/badstorm/surface-pro-7-opencore/issues/9

Once you locate the place, we can try to debug it together.

**Comment by rgallaway** [comment]
Hi, I've spent some time this weekend digging through these threads, and I thought I'd add one more computer to the list of problems. I have a ThinkPad X390 ([20SC000AUS](https://psrefapi.lenovo.com/Detail/ThinkPad/ThinkPad_X390?M=20SC000AUS), UEFI v1.16) that's experiencing the same problem as in this issue and the Surface Pro 7 issue. As with these issues, I tried the various combinations of quirks to no avail. This is all when booting OC from USB, I have not been able to successfully boot macOS on this system. MSR E2 is locked, no option to unlock, so I am using AppleXcpmCfgLock.

I narrowed down the crash using hard resets and RTC writes and here are my findings:
* SetupVirtualMap quirk = TRUE definitely does not work, crashes when writing to PML4 as stated in #719 
* Neither DirectResetHard nor OnRtcWrite execute on the line directly after the call to gRT->SetVirtualAddressMap within AppleMapPrepareMemState with SetupVirtualMap quirk = FALSE
* * I tested OnRtcWrite in a known-good area of the code and it gives a CMOS checksum error on the next boot, which did not happen when I placed the OnRtcWrite directly after SetVirtualAddressMap, so that leads me to believe it's crashing within the call to the Lenovo firmware's SetVirtualAddressMap based on the call sequence you posted on the Surface thread.

I'm not knowledgeable enough about UEFI to know where to go from here (moreso now than 2 days ago, at least), but I'm happy to help debug and hopefully fix this problem. It seems like more and more new-model laptops are experiencing this, so I hope we can get it working.

**Comment by vit9696** [comment]
When you said OnRtcWrite, I assume you actually meant OcRtcWrite?

Now the question is what does exactly fail in our case. I assume some memory types become either unmapped or simply not executable. Could you try calling `gRT->SetVirtualAddressMap` [from OpenRuntime](https://github.com/acidanthera/OpenCorePkg/blob/0.6.6/Platform/OpenRuntime/UefiRuntimeServices.c#L758) as opposed to using `mCustomSetVirtualAddressMap` and then performing a direct reset / RTC write? This will check whether OpenRuntime memory is still available after `gRT->SetVirtualAddressMap`.

Also please provide the current set of quirks you have.

**Comment by rgallaway** [comment]
Yes, I did mean OcRtcWrite. Mistyped it in the comment, but it was correct in the code. Booter quirks are currently set the same as in the screenshot above in this thread, which I believe lines up with the recommendations for Comet Lake systems.

I just tried your suggestion, shown in the screenshot below. Neither the `OcRtcWrite` or the `DirectResetCold` got hit on the line directly below the `gRT->SetVirtualAddressMap`. As a sanity check, I moved the RTC write right above the function call, below the `else`, and I got the checksum error on reboot (so it got to that point in the code, at least). 

<img width="390" alt="Screen Shot 2021-02-14 at 11 48 34 PM" src="https://user-images.githubusercontent.com/13832984/107914460-b833bd80-6f1f-11eb-92ab-0a2bec09e9c8.png">

**Comment by vit9696** [comment]
Very interesting. Please try without SyncRuntimePermissions and RebuildAppleMemoryMap (without first, then without second, then without both). Tell me whether anything changes and you can execute code after SetVirtualAddressMap.

If not, I really need to understand what is going on with the memory map. For this I need you do the following:
1. Run OpenShell before OpenCore (i.e. through firmware menu by e.g. naming it EFI\BOOT\BOOTx64.efi)
2. Take MmapDump.efi tool and run it. Save the output (by >) to a text file.
3. Load OpenRuntime driver (by load fs0:\path\to\OpenRuntime.efi).
4. Create another dump with MmapDump.efi and save it.

Provide both reports here. When OpenRuntime loads you should see its base address printed in the Shell. Please note it, and include it along with the reports. If for some reason it does not print it, print the address of OpenRuntine [UefiEntryPoint](https://github.com/acidanthera/OpenCorePkg/blob/master/Platform/OpenRuntime/OpenRuntime.c).

**Comment by rgallaway** [comment]
I just tried this over my lunch break. I left the code as above -- i.e. OcRtcWrite/DirectResetCold directly after the SetVirtualAddressMap code in OpenRuntime. If this isn't correct, let me know and I can run it again. Each combination of the quirks gave the same result: no RTC writes, no hard resets. 

I've attached the mmap dumps. Loading OpenRuntime printed that it loaded at address 897E9000.
[pre-openruntime.txt](https://github.com/acidanthera/bugtracker/files/5991279/pre-openruntime.txt)
[post-openruntime.txt](https://github.com/acidanthera/bugtracker/files/5991280/post-openruntime.txt)

**Comment by vit9696** [comment]
So, OpenRuntime is indeed not present in the attribute table, but our quirks should fix it. I wonder if the firmware does not inspect some of the values…

Could you try dropping `gRT->SetVirtualAddressMap        = WrapSetVirtualAddressMap;` line in OpenRuntime (UefiRuntimeServices.c)? This will disable the wrap on WrapSetVirtualAddressMap. I wonder if it actually lets you start the kernel (and probably die very quickly).

**Comment by rgallaway** [comment]
I just tried this (had to #if 0 out the whole WrapSetVirtualAddressMap function to make the compiler happy). I spent a while trying to find a good place to test how far I'm getting now, but I can confirm that I'm still not getting to AppleMapPrepareKernelState (RTC write on the first line does not hit). I made sure we're at least getting through OcExitBootServices, but I can't tell what happens between there and AppleMapPrepareKernelState with the SetVirtualAddressMap wrapper disabled.

**Comment by vit9696** [comment]
I am hoping that with most if not all quirks disabled you might be able to reach the onscreen XNU kernel output, but maybe I am wrong indeed. Still try that.

If nothing, let's step back a little. In the latest commit I added `SetupVirtualMap` support for write-protected page tables in the firmwares. This should let you enable `SetupVirtualMap` and see whether you can get past the `SetVirtualAddressMap` call now. Please report that. If you have more ideas of what to test, also feel free to add.

**Comment by rgallaway** [comment]
Alright, I tried various combinations of quirks with no luck. I then pulled your changes, and the kernel is now loading! Looks like we may have found the elusive write-protected firmware that needs SetupVirtualMap :)

The kernel's definitely not happy yet, not sure if this error is related to anything we've done here but I put in a photo just in case. I'm just glad to make some progress. Thanks so much for your help!
![IMG_0864](https://user-images.githubusercontent.com/13832984/108316931-cd585880-717a-11eb-9cf7-51aabd11f2fc.jpg)

**Comment by oceanzhang860411** [comment]
> Alright, I tried various combinations of quirks with no luck. I then pulled your changes, and the kernel is now loading! Looks like we may have found the elusive write-protected firmware that needs SetupVirtualMap :)
> 
> The kernel's definitely not happy yet, not sure if this error is related to anything we've done here but I put in a photo just in case. I'm just glad to make some progress. Thanks so much for your help!
> ![IMG_0864](https://user-images.githubusercontent.com/13832984/108316931-cd585880-717a-11eb-9cf7-51aabd11f2fc.jpg)

Hi, I have a thinkpad L13 and moded bios to unlock cfg lock. Would you please upload your efi here? I willing to have a try. Thank You

**Comment by andreszerocross** [comment]
I will try latest commit tonight, thanks for dev and you @rgallaway

**Comment by vit9696** [comment]
Given that it reached so far, I guess I would close the issue for now as any further issues will likely be a separate thing.

**Comment by andreszerocross** [comment]
I can confirm it's work. Thanks @vit9696
