### ISSUE TITLE
FeatureUnlock - Content Caching Unlock doesn't work on qemu + patching kern.hv_vmm_present breaks AppleQEMUGuestAgent

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1910]
Patch to unlock content caching is breaking AppleQEMUGuestAgent in /usr/libexec/
This is because AppleQEMUGuestAgent depends on kern.hv_vmm_present.
It works again if:

1. copy AppleQEMUGuestAgent to desktop
2. Hex edit the binary replacing kern.hv_vmm_present to virtual_acidanthera
3. Codesign the binary with codesign -f -s - ~/Desktop/AppleQEMUGuestAgent
4. Run AppleQEMUGuestAgent from terminal

Not sure if it can be fixed in some way

**Comment by khronokernel** [comment]
@82ghost82 Appreciate your testing and documenting a solution to this, below I've attached a new build of FeatureUnlock that should resolve this issue:

* [FeatureUnlock-1.0.5-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7799812/FeatureUnlock-1.0.5-DEBUG.zip)

If you can verify it works, will push to the repo

<details>
<summary>Changes made for reference:</summary>

```diff
diff --git a/FeatureUnlock/kern_start.cpp b/FeatureUnlock/kern_start.cpp
index 4ef76df..a7fba13 100644
--- a/FeatureUnlock/kern_start.cpp
+++ b/FeatureUnlock/kern_start.cpp
@@ -95,10 +95,13 @@ static void patched_cs_validate_page(vnode_t vp, memory_object_t pager, memory_o
         }
         // Individual binary patching
         // TODO: Check for presense and value of kern.hv_vmm_present before patching
-        if (allow_assetcache && UNLIKELY(strcmp(path, assetCachePath))) {
-            if (getKernelVersion() >= KernelVersion::Monterey || (getKernelVersion() == KernelVersion::BigSur && getKernelMinorVersion() >= 4)) {
+        if (allow_assetcache && (getKernelVersion() >= KernelVersion::Monterey || (getKernelVersion() == KernelVersion::BigSur && getKernelMinorVersion() >= 4))) {
+            if (UNLIKELY(strcmp(path, assetCachePath))) {
                 searchAndPatch(data, PAGE_SIZE, path, kAssetCacheHypervisorOriginal, kAssetCacheHypervisorPatched, "AssetCache hv_vmm");
             }
+            if (UNLIKELY(strcmp(path, qemuGuestAgentPath))) {
+                searchAndPatch(data, PAGE_SIZE, path, kAssetCacheHypervisorOriginal, kAssetCacheHypervisorPatched, "QEMUAgent hv_vmm");
+            }
         }
     }
 }
diff --git a/FeatureUnlock/kern_usr_patch.hpp b/FeatureUnlock/kern_usr_patch.hpp
index 581faaa..648abdb 100644
--- a/FeatureUnlock/kern_usr_patch.hpp
+++ b/FeatureUnlock/kern_usr_patch.hpp
@@ -14,6 +14,7 @@
 #pragma mark - Binary Paths on disk
 
 static const char *assetCachePath = "/usr/libexec/AssetCache/AssetCache";
+static const char *qemuGuestAgentPath = "/usr/libexec/AssetCache/AppleQEMUGuestAgent";
 
 #pragma mark - Binary Patches
```

</details>
<br>

**Comment by reitermarkus** [comment]
@khronokernel, after your changes now both `AssetCache` and `AppleQEMUGuestAgent` should be patched the same way, so both will think they are *not* in a VM, right? However, `AppleQEMUGuestAgent` should think it *is* running in a VM in order to start.

Before your changes: `AppleQEMUGuestAgent` does not start since it seemingly is patched even though there is a check for `assetCachePath`.

After your changes: `AppleQEMUGuestAgent` does still not start since it is now patched (or is it?) to think it isn't running in a VM.

Without `-allow_assetcache`: `AppleQEMUGuestAgent` starts as expected.

**Comment by reitermarkus** [comment]
Ah, your `qemuGuestAgentPath` is wrong, it should be `/usr/libexec/AppleQEMUGuestAgent`.

**Comment by khronokernel** [comment]
> However, AppleQEMUGuestAgent needs to think it is running in a VM in order to start.

This is why I was confused with the initial issue filed, as shouldn't `AppleQEMUGuestAgent` be checking for `kern.hv_vmm_present`? However @82ghost82 had added a working solution, thus the reason for adding the additional patch for testing.
> your qemuGuestAgentPath is wrong, it should be /usr/libexec/AppleQEMUGuestAgent.

Have you verified adjusting the pathing resolved the issue?

**Comment by 82ghost82** [comment]
Hi all, I noticed the error path yesterday evening but it was too late to test.
First step, I tried the kext to allow asset cache (the release one, debug version), I tried in the past (when it was added this feature to the kext), but I was not able to make it work.
Unfortunately it still doesn't work for me, so I can't test this issue, before I solved the previous one.
Could be a bug or an error on my end:
1. the kext is injected successfully (kextstat)
com.khronokernel.FeatureUnlock (1.0.4) DBC0FFE6-4681-30A3-BEF2-D02F219A76E2 <51 9 7 6 3 2 1>

2. -allow_assetcache is added and it is in the nvram variables for boot-args
boot-args	-allow_assetcache agdpmod=pikera vti=12 keepsyms=1

3. But no patch is applied (Monterey 12.1, but was on Big Sur 11.6.1 when I tried it for the first time)
sysctl -a | grep kern.hv_vmm_present
kern.hv_vmm_present: 1

I need to add some prints to the log to understand why it doesn't patch.


> This is why I was confused with the initial issue filed, as shouldn't `AppleQEMUGuestAgent` be checking for `kern.hv_vmm_present`? However @82ghost82 had added a working solution, thus the reason for adding the additional patch for testing.

The logic for this is:
1. Content caching not available if kern.hv_vmm_present = 1 and also VMM is present in cpu.features --> let's change their name
2. AppleQEMUGuestAgent not starting if kern.hv_vmm_present different than 1 --> let's patch also AppleQEMUGuestAgent to check for what we patched before, so AppleQEMUGuestAgent thinks that kern.hv_vmm_present = 1

**Comment by 82ghost82** [comment]
Even more strange (for me) I can 100% replicate what @reitermarkus wrote:
The new kext with patches for both kern.hv_vmm_present and AppleQEMUGuestAgent works for activating cache content, but (obviously) fails to activate AppleQEMUGuestAgent.

**Comment by khronokernel** [comment]
So a little confused trying to parse this issue. Going to try and break it down, please comment if there's some misinterpretation from my perspective:

1. You are using FeatureUnlock on a system exposing `kern.hv_vmm_present`
2. Without the usage of `-allow_assetcache` argument, AppleQEMUGuestAgent is functional but AssetCache returns an error due to the reporting of `hv_vmm_present`
3. Using the AssetCache patch in FeatureUnlock, you are able to restore caching support however AppleQEMUGuestAgent breaks
4. As @82ghost82 stated in the [initial filing](https://github.com/acidanthera/bugtracker/issues/1910#issue-1091980193), manually patching AppleQEMUGuestAgent to check the same variable as AssetCache resolves the issue
5. Doing the same patch in FeatureUnlock does not work however.

Based off this interpretation, I or someone else must be incorrect. Because at this moment, I fail to understand how manually patching AppleQEMUGuestAgent to a completely non-existant `sysctl` entry resolves this issue. Additionally [the later comments below](https://github.com/acidanthera/bugtracker/issues/1910#issuecomment-1003976967), patching it via FeatureUnlock is unsuccessful. 

So either 4. is false and does not work as initially written, or FeatureUnlock is not correctly patching the binary even with the updated path. 

So I ask, can someone give me a concise explanation? I do not have any QEMU Virtual Machines set up at this time, so I am relying entirely on your comments to understand how best to proceed.

**Comment by 82ghost82** [comment]
Hi khronokernel, sorry if it was not clear, not so easy for me to explain clearly in english. Trying to explain better here.
I tested 2 cases:
case a) kernel patching: https://github.com/ofawx/VmAssetCacheEnable
There are 2 patches:
1. Rename VMM to XXX
2. Rename kern.hv_vmm_present to kern.hv_xxx_present

In this case:
sysctl -a reports kern.hv_xxx_present
cpu.features reports XXX

Content caching can be activated (green dot)
AppleQEMUGuestAgent cannot be started

Workaround for AppleQEMUGuestAgent: copy AppleQEMUGuestAgent from /usr/libexec/ to Desktop (for example), hex edit the binary, replacing hv_vmm_present with hv_xxx_present, code signing it and run it: AppleQEMUGuestAgent can be started without errors.

case b) FeatureUnlock.kext + boot-arg for Content caching
With the currently master version (NOT the version in this discussion)
In addition to the kext I always applied the kernel patch (case a, 1.) to rename VMM to XXX
In this case:
sysctl -a reports kern.hv_vmm_present: 1
cpu.features reports XXX

Content caching can't be activated (yellow dot --> timeout error)
AppleQEMUGuestAgent cannot be started, both original and hex edited edition (replacing kern.hv_xxx_present with virtual_acidanthera)

case b1) FeatureUnlock.kext + boot-arg for Content caching
With the version of this discussion, with path to AppleQEMUGuestAgent fixed in the code to /usr/libexec/AppleQEMUGuestAgent
In addition to the kext I always applied the kernel patch (case a, 1.) to rename VMM to XXX
In this case:
sysctl -a reports kern.hv_vmm_present: 1
cpu.features reports XXX

Content caching can be activated (green dot)
AppleQEMUGuestAgent cannot be started, both original and hex edited edition (replacing kern.hv_xxx_present with virtual_acidanthera)

Answering your questions:
1. YES
2. YES
3. Not 100% correct, see cases b and b1
4. Yes, BUT ONLY FOR KERNEL PATCHES (case a)
5. YES

Thank you very much for your time!

**Comment by khronokernel** [comment]
To avoid blanket string replacements, I believe it would be best to implement RestrictEvent's [`SoftwareUpdate.cpp`](https://github.com/acidanthera/RestrictEvents/blob/master/RestrictEvents/SoftwareUpdate.cpp) hooking, in that instead we patch it to always return `0` when we determine the process to be `AssetCache`.

* [RestrictEvents-1.0.6-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7804413/RestrictEvents-1.0.6-DEBUG.zip)
 
You'll need `-revsbvmm` in your boot-args. I was able to verify this allows content caching in Monterey with kern.hv_vmm_present set to 1. However this was a genuine Mac and not a virtual machine, so adjust accordingly

**Comment by reitermarkus** [comment]
@khronokernel, this fixed it. Both `AssetCache` and `AppleQEMUGuestAgent` are working now.

**Comment by 82ghost82** [comment]
Perfect, I confirm it's working on my end too.
Thank you very much.

**Comment by vit9696** [comment]
@khronokernel please create a PR with the change.

**Comment by khronokernel** [comment]
Please verify the following PR: https://github.com/acidanthera/RestrictEvents/pull/5

* [RestrictEvents-1.0.6-DEBUG.zip](https://github.com/acidanthera/bugtracker/files/7809698/RestrictEvents-1.0.6-DEBUG.zip)
 
AssetCache spoofing is controlled via `-revasset` boot-arg. This should be functional on 11.3+

**Comment by 82ghost82** [comment]
Verified and it works as expected. Thank you.
Moreover, I want to add for others reading this that VMM rename is not needed to have content caching and AppleQEMUGuestAgent working.
![Senza nome](https://user-images.githubusercontent.com/18054052/148116047-1eb4b54a-548f-4d2d-a3e4-0003424d4da9.png)
