### ISSUE TITLE
[VirtualSMC.kext] Missing SMC keys make PerfPowerServices takes 70% CPU on Sequoia 15.4

### ISSUE THREAD

**Issue by Ecco** [acidanthera/bugtracker#2480]
On some machines, running Sequoia 15.4 with VirtualSMC.kext will yield a very slow system because `PerfPowerServices` takes about 70% CPU and `kernel_task` about 40% CPU.

This doesn't happen on every single machine, but it is quite a widespread issue, and many users are reporting this issue:

- On [InsanelyMac](https://www.insanelymac.com/forum/topic/360820-sequoia-154-high-cpu-usage/)
- On [Reddit](https://www.reddit.com/r/hackintosh/comments/1jooykf/macos_sequoia_154_24e248_available/)

Profiling `PerfPowerServices` shows that it is having a hard time getting some SMC keys:

```
    8816 Thread_2299   DispatchQueue_84: com.apple.powerlog.workqueue.PLSMCMetricsAgent  (serial)
    + 8816 start_wqthread  (in libsystem_pthread.dylib) + 15  [0x7ff80f52d843]
    +   8816 _pthread_wqthread  (in libsystem_pthread.dylib) + 298  [0x7ff80f52e8ad]
    +     8816 _dispatch_workloop_worker_thread  (in libdispatch.dylib) + 688  [0x7ff80f3964e3]
    +       8816 _dispatch_root_queue_drain_deferred_wlh  (in libdispatch.dylib) + 275  [0x7ff80f396b96]
    +         8816 _dispatch_lane_invoke  (in libdispatch.dylib) + 382  [0x7ff80f38ddad]
    +           8816 _dispatch_lane_serial_drain  (in libdispatch.dylib) + 779  [0x7ff80f38d35f]
    +             8816 _dispatch_client_callout  (in libdispatch.dylib) + 6  [0x7ff80f39c9fc]
    +               8816 _dispatch_call_block_and_release  (in libdispatch.dylib) + 12  [0x7ff80f3866b9]
    +                 8816 __42-[PLCoreOperator initOperatorDependancies]_block_invoke_2  (in PowerlogCore) + 168  [0x7ff91c87f59b]
    +                   8816 -[PLSMCMetricsAgent initOperatorDependancies]  (in PowerlogLiteOperators) + 119  [0x7ffa0e9f17d2]
    +                     8816 -[PLSMCMetricsAgent getAllKeys]  (in PowerlogLiteOperators) + 97  [0x7ffa0e9f3bc5]
    +                       8816 _dispatch_once_callout  (in libdispatch.dylib) + 20  [0x7ff80f3888ed]
    +                         8816 _dispatch_client_callout  (in libdispatch.dylib) + 6  [0x7ff80f39c9fc]
    +                           8775 __31-[PLSMCMetricsAgent getAllKeys]_block_invoke  (in PowerlogLiteOperators) + 140  [0x7ffa0e9f3c53]
    +                           ! 8755 SMCGetKeyFromIndex  (in libSMC.dylib) + 137  [0x7ff821d83d63]
    +                           ! : 8739 SMCKextCall  (in libSMC.dylib) + 90  [0x7ff821d8352f]
    +                           ! : | 8726 IOConnectCallStructMethod  (in IOKit) + 46  [0x7ff812e5dae9]
    +                           ! : | + 8726 IOConnectCallMethod  (in IOKit) + 248  [0x7ff812e5c9dc]
    +                           ! : | +   8359 io_connect_method  (in IOKit) + 411  [0x7ff812e5cbad]
    +                           ! : | +   ! 8294 mach_msg2_internal  (in libsystem_kernel.dylib) + 83  [0x7ff80f4fe677]
    +                           ! : | +   ! : 8294 mach_msg2_trap  (in libsystem_kernel.dylib) + 10  [0x7ff80f4efb4a]
    +                           ! : | +   ! 64 mach_msg2_internal  (in libsystem_kernel.dylib) + 83,87,...  [0x7ff80f4fe677,0x7ff80f4fe67b,...]
    +                           ! : | +   ! 1 DYLD-STUB$$mach_msg2_internal  (in IOKit) + 0  [0x7ff812f06c80]
    +                           ! : | +   279 io_connect_method  (in IOKit) + 803  [0x7ff812e5cd35]
    +                           ! : | +   ! 270 _platform_memmove$VARIANT$Haswell  (in libsystem_platform.dylib) + 240,0,...  [0x7ff80f5679d0,0x7ff80f5678e0,...]
    +                           ! : | +   ! 8 DYLD-STUB$$_platform_memmove  (in libsystem_platform.dylib) + 0  [0x7ff80f56e87e]
    +                           ! : | +   ! 1 DYLD-STUB$$memcpy  (in IOKit) + 0  [0x7ff812f06ce6]
    +                           ! : | +   73 io_connect_method  (in IOKit) + 415,819,...  [0x7ff812e5cbb1,0x7ff812e5cd45,...]
    +                           ! : | +   7 io_connect_method  (in IOKit) + 131  [0x7ff812e5ca95]
    +                           ! : | +   ! 3 DYLD-STUB$$_platform_memmove  (in libsystem_platform.dylib) + 0  [0x7ff80f56e87e]
    +                           ! : | +   ! 2 DYLD-STUB$$_platform_memmove  (in libsystem_c.dylib) + 0  [0x7ff80f451036]
    +                           ! : | +   ! 2 _platform_memmove$VARIANT$Haswell  (in libsystem_platform.dylib) + 0,71  [0x7ff80f5678e0,0x7ff80f567927]
    +                           ! : | +   4 ___chkstk_darwin  (in libsystem_pthread.dylib) + 17  [0x7ff80f52d86d]
    +                           ! : | +   3 io_connect_method  (in IOKit) + 24  [0x7ff812e5ca2a]
    +                           ! : | +   ! 3 __chkstk_darwin  (in IOKit) + 0  [0x7ff812e5bda0]
    +                           ! : | +   1 io_connect_method  (in IOKit) + 303  [0x7ff812e5cb41]
    +                           ! : | +     1 mig_get_reply_port  (in libsystem_kernel.dylib) + 16  [0x7ff80f4efdcb]
    +                           ! : | 13 IOConnectCallStructMethod  (in IOKit) + 50,0  [0x7ff812e5daed,0x7ff812e5dabb]
    +                           ! : 16 SMCKextCall  (in libSMC.dylib) + 92,90,...  [0x7ff821d83531,0x7ff821d8352f,...]
    +                           ! 19 SMCGetKeyFromIndex  (in libSMC.dylib) + 122,137,...  [0x7ff821d83d54,0x7ff821d83d63,...]
    +                           ! 1 DYLD-STUB$$SMCGetKeyFromIndex  (in PowerlogLiteOperators) + 0  [0x7ffa0ebb07a8]
    +                           26 __31-[PLSMCMetricsAgent getAllKeys]_block_invoke  (in PowerlogLiteOperators) + 126  [0x7ffa0e9f3c45]
    +                           ! 25 objc_msgSend  (in libobjc.A.dylib) + 26,33,...  [0x7ff80f1470da,0x7ff80f1470e1,...]
    +                           ! 1 -[PLSMCMetricsAgent smcConnection]  (in PowerlogLiteOperators) + 11  [0x7ffa0e9f46b0]
    +                           15 __31-[PLSMCMetricsAgent getAllKeys]_block_invoke  (in PowerlogLiteOperators) + 143,112,...  [0x7ffa0e9f3c56,0x7ffa0e9f3c37,...]
    8816 Thread_2306: caulk.messenger.shared:17
```

**Comment by schrup21** [comment]
Hi, thank you for opening the issue. 

I am one of those affected too.

I'd like to add that, according to comments from various users, only iGPU machines may be affected. The issue has been reported on iGPU-only machines, but also on iGPU + dGPU, and even on dGPU with the iGPU disabled in the BIOS - anyway, it seems the missing keys are related to iGPU.

Various workarounds already exist: patched RestrictEvents.kext, with and without bootarg to disable PerfPowerServices, or disabling PerfPowerService via launchctl (which requires disabling SIP).

The issue seems to persist on 15.5 Beta.

**Comment by Ecco** [comment]
> Various workarounds already exist: patched RestrictEvents.kext, with and without bootarg to disable PerfPowerServices, or disabling PerfPowerService via launchctl (which requires disabling SIP).

Indeed, but those workarounds are really "dirty": getting rid of PerfPowerServices altogether doesn't really seem like a satisfactory fix. But thanks for mentioning them though, it definitely can help others until a proper fix is found 😄

**Comment by Ecco** [comment]
Using the DEBUG build of `VirtualSMC.kext` with `-vsmcdbg -vsmcrpt` yields the following logs:

```
[  389.639022]: VirtualSMC    kstore: @ (DBG) key at 2234 not found
[  389.639026]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639029]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639036]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639040]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
[  389.639053]: VirtualSMC      mmio: @ (DBG) read access at 00004005
[  389.639058]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004005: 00000000
[  389.639063]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 00000078: BB080000
[  389.639066]: VirtualSMC      mmio: @ (DBG) write access at 00000078
[  389.639070]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007E: 00008400
[  389.639074]: VirtualSMC      mmio: @ (DBG) write access at 0000007E
[  389.639078]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007F: 00000012
[  389.639081]: VirtualSMC      mmio: @ (DBG) write access at 0000007F
[  389.639085]: VirtualSMC    kstore: @ (DBG) key at 2235 not found
[  389.639088]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639091]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639098]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639102]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
[  389.639116]: VirtualSMC      mmio: @ (DBG) read access at 00004005
[  389.639120]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004005: 00000000
[  389.639126]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 00000078: BC080000
[  389.639129]: VirtualSMC      mmio: @ (DBG) write access at 00000078
[  389.639133]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007E: 00008400
[  389.639136]: VirtualSMC      mmio: @ (DBG) write access at 0000007E
[  389.639139]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007F: 00000012
[  389.639143]: VirtualSMC      mmio: @ (DBG) write access at 0000007F
[  389.639146]: VirtualSMC    kstore: @ (DBG) key at 2236 not found
[  389.639149]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639152]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639159]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639163]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
[  389.639176]: VirtualSMC      mmio: @ (DBG) read access at 00004005
[  389.639181]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004005: 00000000
[  389.639186]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 00000078: BD080000
[  389.639189]: VirtualSMC      mmio: @ (DBG) write access at 00000078
[  389.639193]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007E: 00008400
[  389.639196]: VirtualSMC      mmio: @ (DBG) write access at 0000007E
[  389.639200]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007F: 00000012
[  389.639203]: VirtualSMC      mmio: @ (DBG) write access at 0000007F
[  389.639206]: VirtualSMC    kstore: @ (DBG) key at 2237 not found
[  389.639210]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639213]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639220]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639224]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
[  389.639239]: VirtualSMC      mmio: @ (DBG) read access at 00004005
[  389.639243]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004005: 00000000
[  389.639249]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 00000078: BE080000
[  389.639252]: VirtualSMC      mmio: @ (DBG) write access at 00000078
[  389.639256]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007E: 00008400
[  389.639259]: VirtualSMC      mmio: @ (DBG) write access at 0000007E
[  389.639263]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007F: 00000012
[  389.639266]: VirtualSMC      mmio: @ (DBG) write access at 0000007F
[  389.639269]: VirtualSMC    kstore: @ (DBG) key at 2238 not found
[  389.639272]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639275]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639282]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639286]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
[  389.639303]: VirtualSMC      mmio: @ (DBG) read access at 00004005
[  389.639308]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004005: 00000000
[  389.639314]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 00000078: BF080000
[  389.639318]: VirtualSMC      mmio: @ (DBG) write access at 00000078
[  389.639322]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007E: 00008400
[  389.639326]: VirtualSMC      mmio: @ (DBG) write access at 0000007E
[  389.639329]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007F: 00000012
[  389.639334]: VirtualSMC      mmio: @ (DBG) write access at 0000007F
[  389.639337]: VirtualSMC    kstore: @ (DBG) key at 2239 not found
[  389.639340]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639343]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639351]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639354]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
[  389.639381]: VirtualSMC      mmio: @ (DBG) read access at 00004005
[  389.639387]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004005: 00000000
[  389.639393]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 00000078: C0080000
[  389.639397]: VirtualSMC      mmio: @ (DBG) write access at 00000078
[  389.639401]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007E: 00008400
[  389.639404]: VirtualSMC      mmio: @ (DBG) write access at 0000007E
[  389.639408]: VirtualSMC      prov: @ (DBG) io result page 0 mmio 0000007F: 00000012
[  389.639411]: VirtualSMC      mmio: @ (DBG) write access at 0000007F
[  389.639415]: VirtualSMC    kstore: @ (DBG) key at 2240 not found
[  389.639419]: VirtualSMC      vsmc: @ (DBG) causing interrupt 4B with size 0
[  389.639422]: VirtualSMC      vsmc: @ (DBG) causeInterrupt 0
[  389.639431]: VirtualSMC      mmio: @ (DBG) read access at 00004000
[  389.639435]: VirtualSMC      prov: @ (DBG) io result page 4 mmio 00004000: 00000020
```

**Comment by Ecco** [comment]
I hooked a debugger to `PerfPowerServices` and added a breakpoint in `SMCUInt32ToString` when running on `hw.model: iMac19,1`. Here are the keys that this daemon tries to look up in its `[PLSMCMetricsAgent getAllKeys]` function, in order:

```
#KEY
$Adr
$Num
BATP
BEMB
CLKH
CLKT
CLWK
CRCA
CRCB
CRCC
CRCF
CRCK
CRCR
CRCU
CRCa
CRCb
CRCc
CRCr
CRCu
DPLM
DUSR
EFBM
EFBP
EFBS
EPCI
EVCT
EVHF
EVRD
FAC0
FNum
HBKP
LDKN
LDLG
LDSP
LsNM
MSDW
MSFW
MSPC
MSPP
MSPR
MSPS
MSQC
MSSD
MSSP
MSSW
MSTc
MSTe
MSTf
MSTi
MSTj
MSTm
MSWr
NATJ
NATi
NTOK
OSWD
RBr 
REV 
RGEN
RMAC
RMSN
RMde
RPlt
RSSN
RVBF
RVCR
RVUF
WKTP
PC0C
PC0G
PC0R
PC3C
PCAM
PCEC
PCGC
PCGM
PCPC
PCPG
PCPR
PCPT
PCTR
TC0C
TC0D
TC0E
TC0F
TC0G
TC0H
TC0J
TC0P
TC0c
TC0p
TC1C
TC1c
TC2C
TC2c
TC3C
TC3c
TC4C
TC4c
TC5C
TC5c
TC6C
TC6c
TC7C
TC7c
VC0C
F0Ac
F1Ac
F2Ac
F3Ac
F4Ac
F5Ac
```

**Comment by vit9696** [comment]
Does adding some of these keys help the issue?

**Comment by vit9696** [comment]
It looks like PerfPowerServices constantly reinitialises itself. The exact reason needs to be investigated, but from the logs I think it is probably due to some TCC check failing:

```
default	15:01:40.183387+0300	PerfPowerServices	[0x7ff54e70a3a0] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED
default	15:01:40.183557+0300	PerfPowerServices	[0x7ff55f00a9f0] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED
error	15:01:40.183624+0300	PerfPowerServices	XPC connection interrupted, resetting
error	15:01:40.183545+0300	PerfPowerServices	XPC connection interrupted, resetting
default	15:01:40.438652+0300	PerfPowerServices	Received CBMsgIdReadyForTCC
default	15:01:40.438698+0300	PerfPowerServices	Running performTccCheck CBManager tccAvail 1, tccRequired 0
default	15:01:40.438726+0300	PerfPowerServices	TCC is already complete
default	15:01:59.107970+0300	PerfPowerServices	[0x7ff54e70a3a0] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED
error	15:01:59.108009+0300	PerfPowerServices	XPC connection interrupted, resetting
default	15:01:59.108051+0300	PerfPowerServices	[0x7ff55f00a9f0] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED
error	15:01:59.108108+0300	PerfPowerServices	XPC connection interrupted, resetting
```

It seems to be a coincidence this creates heavy load, because SMC sensor key parsing happens on every PerfPowerServices reload and requires a lot of CPU power.

As a workaround you can disable SMC sensor key support in PerfPowerServices:

```sh
sudo defaults -currentHost write /Library/Preferences/com.apple.powerlogd SMCMonitorCadence 0
```

**Comment by Ecco** [comment]
Awesome, thank you!

> It looks like PerfPowerServices constantly reinitialises itself.

I am under the same impression.

> PerfPowerServices reload and requires a lot of CPU power

Would make sense. My understanding from reading the binary is that SMC info is normally memoized by this process, most likely because fetching it is indeed CPU intensive (for some reason).

> probably due to some TCC check failing

TCC as in [Transparency, Consent and Control](https://atlasgondal.com/macos/priavcy-and-security/app-permissions-priavcy-and-security/a-guide-to-tcc-services-on-macos-sequoia-15-0/)?

Also, how do you come to this conclusion? Just reading the logs you quoted, I don't seem to see any TCC-related problem ("tccAvail 1, tccRequired 0" and "TCC is already complete").

> Does adding some of these keys help the issue?

I don't know! I guess I could come up with a list of keys that PerfPowerServices requests and that VirtualSMC (currently) doesn't have a value for. But then what value should I return?

**Comment by vit9696** [comment]
> TCC as in [Transparency, Consent and Control](https://atlasgondal.com/macos/priavcy-and-security/app-permissions-priavcy-and-security/a-guide-to-tcc-services-on-macos-sequoia-15-0/)?

Yes.

> Also, how do you come to this conclusion? Just reading the logs you quoted, I don't seem to see any TCC-related problem ("tccAvail 1, tccRequired 0" and "TCC is already complete").

I had a suspect based on repetitive messages related to TCC nearby, but that proved to be wrong. The reason for constant XPC restart at least on my machine were bluetooth issues. I do not use bluetooth and had it disabled, but for some reason IOBluetoothFamily starts a dummy HCI interface even in this case. It is possible to entirely disable this with the following patch:

```
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>Base</key>
				<string>__ZN24IOBluetoothHCIController5startEP9IOService</string>
				<key>Comment</key>
				<string>Disable Bluetooth entirely</string>
				<key>Count</key>
				<integer>1</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data></data>
				<key>Identifier</key>
				<string>com.apple.iokit.IOBluetoothFamily</string>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>Replace</key>
				<data>ww==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
			</dict>
```

Afterwards I do not get any messages from PerfPowerServices on a regular basis, even with debug enabled:

```sh
sudo defaults -currentHost write /Library/Preferences/com.apple.powerlogd debugEnabled -bool true
```

However, it still regularly gets stuck in initOperatorDependancies `-[PLCoreOperator initOperatorDependancies]` blocks.

**Comment by vit9696** [comment]
The good news we can also enable additional levels of logging without disabling SIP. E.g. by adding `/Library/Preferences/Logging/Subsystems/com.apple.PerfPowerServicesAgent.plist` with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>smcmetrics</key>
	<dict>
		<key>Level</key>
		<dict>
			<key>Persist</key>
			<string>Debug</string>
			<key>Enable</key>
			<string>Debug</string>
		</dict>
		<key>Enable-Oversize-Messages</key>
		<true/>
	</dict>
</dict>
</plist>
```

Needs a reboot after editing this. More details on `man 5 os_log`. So far it did not give me much.

**Comment by vit9696** [comment]
Please test VirtualSMC.kext from master, should be fixed.

You can revert the effects of the previous command by executing:

```
sudo defaults -currentHost delete /Library/Preferences/com.apple.powerlogd SMCMonitorCadence
```

**Comment by SergeySlice** [comment]
Thank you for the investigation!

**Comment by dattran1232003** [comment]
Hello, I can confirm after doing these, I no longer see PerfPerformanceServices running and consuming high CPU usage anymore.
![Image](https://github.com/user-attachments/assets/c37f4104-e3a9-41b0-8340-2857116a095d)

**Step 1**
```
sudo defaults -currentHost write /Library/Preferences/com.apple.powerlogd debugEnabled -bool true
```

**Step 2**
> The good news we can also enable additional levels of logging without disabling SIP. E.g. by adding `/Library/Preferences/Logging/Subsystems/com.apple.PerfPowerServicesAgent.plist` with the following content:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>smcmetrics</key>
> 	<dict>
> 		<key>Level</key>
> 		<dict>
> 			<key>Persist</key>
> 			<string>Debug</string>
> 			<key>Enable</key>
> 			<string>Debug</string>
> 		</dict>
> 		<key>Enable-Oversize-Messages</key>
> 		<true/>
> 	</dict>
> </dict>
> </plist>
> ```
> 
> Needs a reboot after editing this. More details on `man 5 os_log`. So far it did not give me much.

**Comment by AngeloAvv** [comment]
@vit9696 I'm experiencing PerfPowerServices process reaching nearly 100% CPU on a macOS 15.5 VM running on Proxmox 8.4.1 using thenickdude's [OpenCore-v21 EFI](https://github.com/thenickdude/KVM-Opencore/releases/tag/v21). Replacing VirtualSMC.kext v1.3.6 didn't fix the problem

**Comment by sieskei** [comment]
@AngeloAvv 
These pre-built OpenCore EFIs for KVM use outdated configurations from years ago.
Update to version 1.3.6 and remove the following line from your virtual machine configuration to fix it:
`-device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"`

**Comment by vscfreire** [comment]
@sieskei Removing that line renders the machine unbootable in Proxmox (8.4.1) with stock OpenCore 1.0.4 and VirtualSMC.kext v1.3.6.

**Comment by fragfeaster777** [comment]
I too have issues with PerfPowerServices and VirtualSMC.kext v1.3.6 when running anything above Sequoia 15.3.1 in a Proxmox VM.

The issue continues to be an infinite loop of errors in getting SMC keys:

`2025-06-13 11:53:54.753 E kernel [0:898] kernel [0:898 (AppleSMC) AppleSMCFamily::handleSMCResult ERROR in smcGetKeyFromIndexPM1O. 5517 kSMCBadCommand (0x82)`

I tried @sieskei suggestion of removing the `-device...` arguments, but the machine would get stuck at boot:

`'AppleKeyStore": 12667:152: operation failed (sel: 7 ret: e00002f0, -1)`

**Comment by vscfreire** [comment]
> I too have issues with PerfPowerServices and VirtualSMC.kext v1.3.6 when running anything above Sequoia 15.3.1 in a Proxmox VM.
> 
> The issue continues to be an infinite loop of errors in getting SMC keys:
> 
> `2025-06-13 11:53:54.753 E kernel [0:898] kernel [0:898 (AppleSMC) AppleSMCFamily::handleSMCResult ERROR in smcGetKeyFromIndexPM1O. 5517 kSMCBadCommand (0x82)`
> 
> I tried [@sieskei](https://github.com/sieskei) suggestion of removing the `-device...` arguments, but the machine would get stuck at boot:
> 
> `'AppleKeyStore": 12667:152: operation failed (sel: 7 ret: e00002f0, -1)`

You have to remove the device line and then activate the SMC module in OpenCore configs.

**Comment by fragfeaster777** [comment]
@vscfreire, thanks for replying - I actually modify the config.plist directly, but still no luck booting without the `-device...` line in.

In case it's relevant: 

- VirtualSMC is loaded as the second kext (after Lilu). I'm using Opencore 1.0.4
- The whole CM args are: `-device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" -smbios type=2 -device qemu-xhci -device usb-kbd -device usb-tablet -global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off -cpu 'host,vendor=GenuineIntel,+invtsc,+hypervisor,vmware-cpuid-freq=on'`
