### ISSUE TITLE
VoodooPS2controller - two finger secondary click not working

### ISSUE THREAD

**Issue by JayMonkey** [acidanthera/bugtracker#342]
Hi Guys,

I have 2017 HP Spectre X360 Laptop with Synaptics Click pad

have been using rehabmans voodoops2controller kext for a few years now, but it hasn't been updated in a while and suffers from a few issues such as scrolling can sometimes get a bit jittery and not all gestures work such as pinch zoom, smart zoom .. etc

I came across your VoodooPS2 project through a post at TMx86 and decided to give it a try.

Two finger scrolling is way better including coast and its nice to finally have gestures like two finger pinch zoom and auto zoom working .. great job !

However when Secondary click is set as two fingers it does not work, which seems odd as other two finger gestures such as scroll and zoom work just fine. Setting the secondary click to left or right corner works fine though as does a single finger normal click

I'm not using tap to click or the force click features (unchecked in tackpad pref panel)
The two finger secondary click works fine with rehabmans version.

Also i've noticed that it does not always play nice with VoodooIC which i have installed to enable the screen's touch feature and more importantly the active stylus. seems to cause VoodooI2C kext to stall during MacOS boot .. not always but most times ( maybe 4 out of 5 attempts)

I think your version of VoodooPS2Controller has the potential to be a much better solution for PS2 tackpads/clickpads once it plays nice with VoodooI2C and the few reported issues are resolved.

Happy to provide additional info and debug if you tell me what you need.

Cheers
Jay

**Comment by junaedahmed** [comment]
Facing somewhat same problem though in my case two finger secondary click works but slow and doesn't work all the time 2 out of 5 times it fails to register.

I have Thinkpad t460 with synaptic touchpad. also drag lock in accessibility option doesn't work.

**Comment by usr-sse2** [comment]
@JayMonkey, does two finger tap (not click) work as secondary click if tap to click is enabled?

**Comment by JayMonkey** [comment]
> @JayMonkey, does two finger tap (not click) work as secondary click if tap to click is enabled?

I cant remember if i tried that ....

I'll reinstall the latest version of your VoodooPS2Controller kext and check ....

Cheers
Jay

**Comment by JayMonkey** [comment]
> @JayMonkey, does two finger tap (not click) work as secondary click if tap to click is enabled?

Hi Michael,

Download VoodooPS2Controller sources and built in Xcode, replaced rehabmans version with yours.

With "Tap to Click" enabled, two finger tap for secondary click does but its a bit hit and miss .. seems very unresponsive, with maybe 1 in 5-6 attempts working, and it still does not work at all when trying a full secondary click (two finger press down on click pad).

The only other issue i found with the current build is that it stopped VoodooI2C working so my touch screen and pen no longer worked. I'm using the latest 2.2 build of VoodooI2C.

Other than the above issues all other features seem to work well.

Mouse cursor is much more responsive and a lot of the gestures  that didi not work with rehabmans version work well with your version, such as two finger pinch zoom, swipe between pages ... etc.

Happy to test and provide further debug if you need it.

Cheers
Jay

**Comment by usr-sse2** [comment]
> The only other issue i found with the current build is that it stopped VoodooI2C working so my touch screen and pen no longer worked. I'm using the latest 2.2 build of VoodooI2C.
That's very strange. The release build really prevented functioning of VoodooI2C because it provided modified versions of the same classes, but current version fixes it by renaming VoodooI2C classes to VoodooPS2.

**Comment by usr-sse2** [comment]
> With "Tap to Click" enabled, two finger tap for secondary click does but its a bit hit and miss .. seems very unresponsive, with maybe 1 in 5-6 attempts working

What gesture do unsuccessful attempts trigger? Scroll?

**Comment by JayMonkey** [comment]
Hi Michael,

Apologies i actually down loaded the 2.0.1.1 sources by mistake on that last test.

Have just downloaded the master build, compiled and installed and it am happy to report that it works alongside VoodooI2C without any issues ... nice job.

The issue with the two finger secondary click remains though, as a 'tap' two finger click it works maybe 1 in 6 attempts (is very frustrating) and does not work at all as a full two finger 'press' click.

Since this version plays nicely with VoodooI2C i'm going to leave it installed and for now have set the bottom right corner as the secondary click (Note: this never worked with rehabmans version).

Will get some mileage on testing its features and for stability, sleep .. etc.

Will report back if i find any other issues.

Cheers
Jay

**Comment by usr-sse2** [comment]
I suppose that the cause is that only one finger is reported as pressing the button. I'll try it in the next few days.

**Comment by JayMonkey** [comment]
> I suppose that the cause is that only one finger is reported as pressing the button. I'll try it in the next few days.

Let me know if you want me to test anything or supply any additional debug.

Cheers
Jay

**Comment by JayMonkey** [comment]
> One thing I like to point out to this problem is that two-finger tap when doesn't work it registers a one-finger tap most of the time. I noticed it when, I selected some text and performed a two-finger tap for secondary click to copy the text. But most of the time lost the text selection.

Yes that does seem to be what is happening as suspected by Michael (see his reply 3 posts above)

Jay

**Comment by junaedahmed** [comment]
> Yes that does seem to be what is happening as suspected by Michael (see his reply 3 posts above)
> 
> Jay

Sorry my bad, he mentioned button so I thought, he might be talking about the physical button click issue.

**Comment by usr-sse2** [comment]
@JayMonkey, fixed in master (b9d443e7b397d9573b23663910dcc94ee37c02a8)

**Comment by junaedahmed** [comment]
Hi Michael (@usr-sse2),

I have built and tested with above commit. this build solved the two-finger tap recognized as one-finger tap (I can select text and right click on it with out being unselected) but the two-finger tap click still miss 50 % of the time. Hope it helps.

Thanks for your tremendous work.

**Comment by JayMonkey** [comment]
> @JayMonkey, two-finger and three-finger **click** fixed in master (b9d443e7b397d9573b23663910dcc94ee37c02a8)

Hi Michael,

Just tested the latest master build . :-

Two finger 'press' click .. working great now.

Two finger 'tap' click ... works almost all the time but with a very slight delay compared to the 'press' click .. at a guess no more than 0.3 - around 0.5 of a second, its not really an issue but odd that it's not quite as responsive as the 'press' click.

Still have issues with sleep .. see comment in [sleep specific thread](https://github.com/acidanthera/bugtracker/issues/334#issuecomment-510864469)

So close now .... just the sleep issue remains.

Cheers
Jay

**Comment by usr-sse2** [comment]
Yes, it has the delay on my computer too. I'll check if there is such a delay on MacBook Air.

**Comment by JayMonkey** [comment]
Just installed version 2.0.3 ...

Two finger tap click seems to be working much better than it did in 2.0.2
Also gestures seems to work a little better too.

Really great work guys ....

Cheers
Jay

**Comment by soumaxetuirk** [comment]
hello, I am using released debug version 2.0.4 with OSX 10.15 on a Lenovo Ideapad 310. I have a PS2 synaptic touchpad (SYN2B8E). Two finger tap , scroll and gestures are not recognised. three finger tap and gestures are working fine. I was using rehabman's kext before , two finger scrolling and tap were working fine.Now two finger are registering as single finger. double finger tap resulting single finger tap.and double finger scroll is resulting cursor  movement. Also physical buttons are not working.(physical buttons giving no response in system log).
