### ISSUE TITLE
[VoodooPS2] Mouse/touchpad stops responding after trying to perform any multi-finger gesture

### ISSUE THREAD

**Issue by matt-curtis** [acidanthera/bugtracker#826]
It doesn't have to be a complex gesture either — simply a two-finger tap will do it. The physical left and right touchpad buttons don't work either (but that's from the very start, before any gesture has been attempted.) For the moment I've moved back to using RehabMan's VoodooPS2Controller, which doesn't have the same issue.

**Comment by midi1996** [comment]
I have the same issue on my Thinkpad P50 (hard surface touchpad with 3 buttons). One finger movement works, but the moment another finger touches the surface it breaks. I'll attach logs in a moment, but from what I saw the VoodooPS2 driver recognises the finger touches (and the correct number of them) even when it's broken.

**Comment by midi1996** [comment]
Here are the logs:
[Log after boot: PS2_boot.txt](https://github.com/acidanthera/bugtracker/files/4489883/PS2_boot.txt)
[test.txt](https://github.com/acidanthera/bugtracker/files/4489888/test.txt) (by following #557 https://github.com/acidanthera/bugtracker/issues/557#issuecomment-552468245)
[VPS2_stream2.txt](https://github.com/acidanthera/bugtracker/files/4489895/VPS2_stream2.txt) by touching from left to right one finger at a time until 4. 

Btw, just asking, wouldnt using the SMBUS better than PS2? Most laptops with PS2 actually run the trackpad in SMBUS mode (seen by synaptics control panel as SBUS).

**Comment by usr-sse2** [comment]
Is there any documentation or Linux source for SMBus mode? Synaptics PS/2 TouchPad Interfacing Guide says nothing about that.

**Comment by usr-sse2** [comment]
Please check with VoodooInput built from the current master. It seems like a similar issue was resolved there.

**Comment by midi1996** [comment]
> Is there any documentation or Linux source for SMBus mode? Synaptics PS/2 TouchPad Interfacing Guide says nothing about that.

https://github.com/leo-labs/VoodooSMBus I was thinking about this project as it happens my SMBUS IDs are in the driver itself however I use Synaptics and not ELAN, so yeah.

> Please check with VoodooInput built from the current master. It seems like a similar issue was resolved there.

Ok, I will, thanks!

**Comment by midi1996** [comment]
> Please check with VoodooInput built from the current master. It seems like a similar issue was resolved there.

Indeed I compiled VInput in my own and it did fix the sudden lock up, however there is no multitouch support, idk if something went wrong while compiling, here is the result of the logs (Vinput and VPS2 have been compiled with `-configuration Debug`)

[PS2_newInp.txt following https://github.com/acidanthera/bugtracker/issues/557#issuecomment-552468245](https://github.com/acidanthera/bugtracker/files/4511322/PS2_newInp.txt)
[vps2-Tue Apr 21 16:32:12 +00 2020.txt Boot log](https://github.com/acidanthera/bugtracker/files/4511324/vps2-Tue.Apr.21.16.32.12.%2B00.2020.txt)
[VoodooPS2Controller-2.1.4-DEBUG.zip Compiled binaries](https://github.com/acidanthera/bugtracker/files/4511332/VoodooPS2Controller-2.1.4-DEBUG.zip)

**Comment by midi1996** [comment]
![image](https://user-images.githubusercontent.com/4874726/79895001-c2ffed80-83f5-11ea-8233-01a11a1c399e.png)

Using better touch shows only one finger. When moving, the blob would follow the movement and as soon as I put another finger it stops and still shows 1 finger. Here is a video on how it looks like

[Video link](https://cdn.discordapp.com/attachments/573338611337003018/702210586288586852/Screen_Recording_2020-04-21_at_17.31.29.mov)

**Comment by usr-sse2** [comment]
Your touchpad doesn't send extended packets, so it's not in Extended W mode. Try Tarik02's version: he hardcoded the mode, because his touchpad also doesn't report that it supports extended W.
https://github.com/Tarik02/VoodooPS2/tree/my

**Comment by midi1996** [comment]
> Your touchpad doesn't send extended packets, so it's not in Extended W mode. Try Tarik02's version: he hardcoded the mode, because his touchpad also doesn't report that it supports extended W.
> https://github.com/Tarik02/VoodooPS2/tree/my

it appears that we have the same laptop too (Thinkpad P50), I tried his modifications but it's a bit janky especially when using two fingers gesture (zooming and rotating, zooming mainly since that's why I use the most). The buttons do not work anymore even if I set `isTrackpad` in the SSDT. I dont know if the fact that it's quite behind the main repo is a good idea either. Thanks.

**Comment by usr-sse2** [comment]
I found why it didn't enable Extended W mode. It enabled it only for ClickPads (buttonless trackpads where whole surface is clickable, like on Lenovo Yoga or MacBooks before Force Touch). As Extended W mode is required for multitouch, I removed that check by acidanthera/VoodooPS2@8242476230a5592cfedd9960afc2028fca8a57d7. Please check if it works.

**Comment by midi1996** [comment]
> I found why it didn't enable Extended W mode. It enabled it only for ClickPads (buttonless trackpads where whole surface is clickable, like on Lenovo Yoga or MacBooks before Force Touch). As Extended W mode is required for multitouch, I removed that check by [acidanthera/VoodooPS2@8242476](https://github.com/acidanthera/VoodooPS2/commit/8242476230a5592cfedd9960afc2028fca8a57d7). Please check if it works.

Oh yeah! It works! Thanks. I have some work to do atm so I didnt gather any logs, will send them asap. Thanks again!

**Comment by usr-sse2** [comment]
For buttons, I think Tarik02 knows better because I have no such hardware, so it would be better to move further discussion of buttons to #557.

**Comment by midi1996** [comment]
Thanks again! I will see what can be done.
