### ISSUE TITLE
After commit "Added AppleEvent mouse support" OpenCanopy is no more accessible

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#846]
Opencore version: developer, compiled as of today with latest commit [02414e6](https://github.com/acidanthera/OpenCorePkg/commit/02414e60d5606ccb8b41346e1627b46cbc850c7e)
Platform: kvm/qemu enviroment, version 4.2.

With commit [20fa82d](https://github.com/acidanthera/OpenCorePkg/commit/20fa82da4285fb66059a75ef341680cc643d29f7) my system is not able to access OpenCanopy anymore: all I have is a black screen, pressing enter key on keyboard does nothing.
With commit [c85b332](https://github.com/acidanthera/OpenCorePkg/commit/c85b332ac0bd73c0b23eaca730b1be98255824d6) is the same, but I can see the mouse cursor in the upper left corner, frozen.
OpenCanopy was working well before commit 20fa82d.
OCBinaryData is updated.
Moreover, I can't boot with Target 83 because of [this issue](https://github.com/acidanthera/bugtracker/issues/831) so I don't know how to get a log, to be of more help.
I'm open to do all tests you propose.
Thanks

**Comment by vit9696** [comment]
What configuration do you have? In particular I am interested in UEFI → Input section. What is your `TimerResolution`? Did you try other values e.g. lower/higher/0? So far we were unable to observe any issues with these commits on real hardware.

As for logging you can always use serial or file logging.

**Comment by 82ghost82** [comment]
Unfortunately I'm not able to boot with Target 65, so I can't log to file.
Attached my config with some parts redacted.
[config.txt](https://github.com/acidanthera/bugtracker/files/4485689/config.txt)

**Comment by zijun-he** [comment]
TimerResolution=0 --> black screen, no mouse pointer visible, enter macos
[opencore-2020-04-16-122311.txt](https://github.com/acidanthera/bugtracker/files/4487008/opencore-2020-04-16-122311.txt)

**Comment by vit9696** [comment]
Resolved in master, thank you.

**Comment by zijun-he** [comment]
Sorry to bother you again. Use the latest build compilation file to get basically the same result.
![IMG_5441](https://user-images.githubusercontent.com/52475027/79534262-aa699d80-80ac-11ea-93c3-3bdbb06aaf01.JPG)
[opencore-2020-04-17-050407.txt](https://github.com/acidanthera/bugtracker/files/4491008/opencore-2020-04-17-050407.txt)

**Comment by vit9696** [comment]
Note this post:

> Update: With ShowPicker=true icons are visible, mouse pointer in upper left corner, mouse is frozen, keyboard is frozen too

Mose likely you have incorrect configuration.

**Comment by 82ghost82** [comment]
Partially solved for me:
the mouse now works, the icons seems to be invisible, but they are not, see attached pictures.
This with ShowPicker=false
Icons seem invisible
![IMG_20200417_083825](https://user-images.githubusercontent.com/18054052/79539990-ac6d3580-8087-11ea-8731-3e2a89eedb74.jpg)

![IMG_20200417_083818](https://user-images.githubusercontent.com/18054052/79540028-bc851500-8087-11ea-8536-0fa67df4f304.jpg)

**Comment by vit9696** [comment]
Yes, I indeed can reproduce it with ShowPicker = NO. For the time being you could workaround it with ShowPicker = YES. Since this is a separate issue, could you file another bug for it?

**Comment by 82ghost82** [comment]
Yes, opening now. Thank you very much for your work

**Comment by zijun-he** [comment]
For me ShowPicker = true / false are the same result

**Comment by 82ghost82** [comment]
@zijun-he 
Better to write to the forum? In the meantime you can check if you added the new usb driver to your config.
