### ISSUE TITLE
Booting on legacy BIOS with bootstrap.efi breaks KeySupport

### ISSUE THREAD

**Issue by kommtzeitkonrad** [acidanthera/bugtracker#870]
https://github.com/acidanthera/OpenCorePkg/commit/a1f60694c7c5fb07392529fa600d939dd916a81b (booting with `Bootstrap.efi` instead of `BOOTx64.efi`) completely breaks support of PS2 keyboard on an HM67 board. Using a USB keyboard together with `OpenUsbKbDxe.efi` driver works. `Ps2MouseDxe.efi` driver does nothing.

[opencore-2020-04-24-154614.txt](https://github.com/acidanthera/bugtracker/files/4530086/opencore-2020-04-24-154614.txt)

Keyboard behavior before the mentioned commit (booting with `BOOTx64.efi`) was the following:

- `KeySupport=true` : PS2 works, USB works
- `OpenUsbKbDxe.efi`: PS2 keypresses are ignored randomly, USB works
- `Ps2MouseDxe.efi`: PS2 keypresses are ignored randomly, USB works

**Comment by roddy20** [comment]
[boot_with_Ps2KeyboardDxe.efi.zip](https://github.com/acidanthera/bugtracker/files/4530190/boot_with_Ps2KeyboardDxe.efi.zip)
try this

**Comment by ameenjuz** [comment]
i set BootProtect to None but my windows partition completely disappear from boot menu
am i missing something?

**Comment by kommtzeitkonrad** [comment]
> [boot_with_Ps2KeyboardDxe.efi.zip](https://github.com/acidanthera/bugtracker/files/4530190/boot_with_Ps2KeyboardDxe.efi.zip)
> try this

Works!

[opencore-2020-04-24-181924.txt](https://github.com/acidanthera/bugtracker/files/4530791/opencore-2020-04-24-181924.txt)

**Comment by kommtzeitkonrad** [comment]
> `Ps2MouseDxe.efi` driver does nothing.

Just remembered that this driver is for touchpad support and of course does nothing regarding keyboard support. Anyway, it may be of interest that the touchpad on an HM67 laptop does not work with or without this driver. On the other side, a USB mouse does work in any configuration without an additional `.efi` driver, except when using `boot` from https://github.com/acidanthera/OpenCorePkg/commit/a1f60694c7c5fb07392529fa600d939dd916a81b.

---
@roddy20: Did the filename of your `.zip` file implied to use `Ps2KeyboardDxe.efi` from MdeModulePkg? Ⅰ build it with

`build -a X64 -b DEBUG -t XCODE5 -p OpenCorePkg/UDK/MdeModulePkg/MdeModulePkg.dsc -m OpenCorePkg/UDK/MdeModulePkg/Bus/Isa/Ps2KeyboardDxe/Ps2KeyboardDxe.inf`

and it does not bring back keyboard support. Only setting the above mentioned `KeySupport=true` together with your `boot` file works.

**Comment by vit9696** [comment]
Ps2KeyboardDxe from UDK should work fine with `KeySupport=true`. We will not enable Ps2KeyboardDxe in DuetPkg due to compatibility issues, you can add it to `Drivers` though. To make it easier I added Ps2KeyboardDxe in OpenCorePkg packaging.

**Comment by kommtzeitkonrad** [comment]
> Ps2KeyboardDxe from UDK should work fine with `KeySupport=true`.

It not only works fine. Finally `PollAppleHotKeys` works, too. No more fiddling around to get verbose output or to get into safe mode. Very nice!

Anyways, the only working `boot` file that works is [the one](https://github.com/acidanthera/bugtracker/issues/870#issuecomment-619118719) from @roddy20's post: [opencore-2020-04-26-143302.txt](https://github.com/acidanthera/bugtracker/files/4535502/opencore-2020-04-26-143302.txt)

With `boot` from https://github.com/acidanthera/OpenCorePkg/commit/a1f60694c7c5fb07392529fa600d939dd916a81b keyboard is not working: 
[opencore-2020-04-26-144005.txt](https://github.com/acidanthera/bugtracker/files/4535529/opencore-2020-04-26-144005.txt)

With `boot` from https://github.com/acidanthera/OpenCorePkg/commit/f21f3c329910f719e3e6378e998333057d544827 keyboard is not working: 
[opencore-2020-04-26-145212.txt](https://github.com/acidanthera/bugtracker/files/4535557/opencore-2020-04-26-145212.txt)

Ⅰ see that you all are busy commiting to [DuetPkg](https://github.com/acidanthera/DuetPkg). Ⅰ will be patient. Thanks for all your efforts. Ⅰ love to use your software/tools and learn from everything around them. :-)

**Comment by vit9696** [comment]
I.e. the only way to get keyboard working for you is to use the boot by Rodion with `KeySupport=true` and avoid adding any PS/2 drivers?

**Comment by vit9696** [comment]
If so, could you check whether this driver works for you with DuetPkg from [OpenCorePkg master](https://github.com/acidanthera/OpenCorePkg/commit/f21f3c329910f719e3e6378e998333057d544827). I extracted it from Rodion's booter: [Ps2KeyboardDxe-clv.zip](https://github.com/acidanthera/bugtracker/files/4535765/Ps2KeyboardDxe-clv.zip).

**Comment by vit9696** [comment]
Actually reproduced and fixed on our end:

```
[master 75443ac] BootInstall: Fix ISA bus support
 1 file changed, 0 insertions(+), 0 deletions(-)
```

The need for Ps2KeyboardDxe holds of course.

**Comment by kommtzeitkonrad** [comment]
Ⅰ was in the middle of a series of measurements:

> `boot` from https://github.com/acidanthera/bugtracker/issues/870#issuecomment-619118719 + `Ps2KeyboardDxe.efi` from `OpenCorePkg` + `KeySupport=true`:
> -> Keyboard works, `PollAppleHotKeys` works
> => [opencore-2020-04-26-160559.txt](https://github.com/acidanthera/bugtracker/files/4535842/opencore-2020-04-26-160559.txt)
> 
> `boot` from https://github.com/acidanthera/bugtracker/issues/870#issuecomment-619118719 + `KeySupport=true`:
> -> Keyboard works, `PollAppleHotKeys` works
> => [opencore-2020-04-26-162241.txt](https://github.com/acidanthera/bugtracker/files/4535930/opencore-2020-04-26-162241.txt)
> 
> `boot` from https://github.com/acidanthera/OpenCorePkg/commit/f21f3c329910f719e3e6378e998333057d544827 + `Ps2KeyboardDxe.efi` from `OpenCorePkg' + `KeySupport=true`:
> -> Keyboard does not work
> => [opencore-2020-04-26-165015.txt](https://github.com/acidanthera/bugtracker/files/4535984/opencore-2020-04-26-165015.txt)

Will try https://github.com/acidanthera/OpenCorePkg/commit/75443ac52e2e76250f596381f023a296be360259.

**Comment by kommtzeitkonrad** [comment]
When using `boot` from https://github.com/acidanthera/OpenCorePkg/commit/75443ac52e2e76250f596381f023a296be360259 and `.efi` drivers from `OpenCorePkg/macbuild.tool` the following is observed:

`KeySupport=true` only:
-> Keyboard does not work.
=> [opencore-2020-04-26-172245.txt](https://github.com/acidanthera/bugtracker/files/4536045/opencore-2020-04-26-172245.txt)

`KeySupport=true` + `Ps2KeyboardDxe.efi`:
-> Keyboard works
-> `PollAppleHotKeys` works
=> [opencore-2020-04-26-174508.txt](https://github.com/acidanthera/bugtracker/files/4536363/opencore-2020-04-26-174508.txt)

`KeySupport=true` + `Ps2KeyboardDxe.efi` + `Ps2MouseDxe.efi`:
-> Keyboard works
-> `PollAppleHotKeys` works
=> [opencore-2020-04-26-173710.txt](https://github.com/acidanthera/bugtracker/files/4536347/opencore-2020-04-26-173710.txt)

-> Touchpad does not work in any configuration.
-> USB mouse works in every configuration (`UsbMouseDxe.efi` is absent).

**Comment by vit9696** [comment]
Right, this is expected. Thanks!

**Comment by kommtzeitkonrad** [comment]
Thank you!

However, I've got more. :-)

Only booting to macOS works. All other operating systems fail to boot.

```
08:866 03:406 OCB: Should boot from Ubuntu (T:32|F:0|DEF:0)
08:869 00:003 OCB: Perform boot Ubuntu to dp PcieRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0x0,0x0)/HD(1,GPT,F729BC2E-FB67-4AFA-8C40-C6F288D47673,0x800,0x113000)/\EFI\ubuntu\grubx64.efi (0/0)
08:871 00:002 OCB: LoadImage failed - Not Found
```
```
04:255 03:059 OCB: Should boot from Windows (T:32|F:0|DEF:0)
04:258 00:002 OCB: Perform boot Windows to dp PcieRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0x0,0x0)/HD(1,GPT,F729BC2E-FB67-4AFA-8C40-C6F288D47673,0x800,0x113000)/\EFI\Microsoft\Boot\bootmgfw.efi (0/0)
04:260 00:001 OCB: LoadImage failed - Not Found
```
Both `.efi` files are present and booted fine before.
```
% ls -l /Volumes/EFI/EFI/ubuntu/grubx64.efi 
-rwxrwxrwx  1 konrad  staff  1668984 20 Mär 02:11 /Volumes/EFI/EFI/ubuntu/grubx64.efi
```
```
% ls -l /Volumes/EFI/EFI/Microsoft/Boot/bootmgfw.efi
-rwxrwxrwx  1 konrad  staff  1557816  7 Dez 10:08 /Volumes/EFI/EFI/Microsoft/Boot/bootmgfw.efi
```

**Comment by vit9696** [comment]
Yeah, I fixed Pci/Pcie bug that existed before. You will need to update your device paths.

**Comment by kommtzeitkonrad** [comment]
Nice! `Entries` now do boot.

I've got two more things not working until https://github.com/acidanthera/OpenCorePkg/commit/cd302ebe50126ce5864a29aa92fc6b3585ab80b9.
1. `BlessOverride=\EFI\Microsoft\Boot\bootmgfw.efi` is ignored.
-> [opencore-2020-04-27-065148.txt](https://github.com/acidanthera/bugtracker/files/4537992/opencore-2020-04-27-065148.txt)
2. Almost all memory pages are system reserved.
-> [memmap-2020-04-27-065148.txt](https://github.com/acidanthera/bugtracker/files/4537990/memmap-2020-04-27-065148.txt)

Most recent `boot` that does not ignore `BlessOverride` and has normal memory map is @roddy20's upload in https://github.com/acidanthera/bugtracker/issues/870#issuecomment-619118719.
-> [memmap-2020-04-27-065528.txt](https://github.com/acidanthera/bugtracker/files/4538023/memmap-2020-04-27-065528.txt)
-> [opencore-2020-04-27-065528.txt](https://github.com/acidanthera/bugtracker/files/4538024/opencore-2020-04-27-065528.txt)

**Comment by vit9696** [comment]
1. Please file a new issue about memory map.
2. As for BlessOverride, please elaborate what do you mean. Is it boot-specific? What do you mean under BlessOverride not working, describe the configuration and so on.

**Comment by kommtzeitkonrad** [comment]
> Please file a new issue about memory map.

https://github.com/acidanthera/bugtracker/issues/877
> As for BlessOverride, please elaborate what do you mean. Is it boot-specific? What do you mean under BlessOverride not working, describe the configuration and so on.

https://github.com/acidanthera/bugtracker/issues/878

**Comment by NeoBlizzard-verbose** [comment]
Although this issue is closed, I still face the issue on my Lenovo G570 (Legacy BIOS). Currently on OpenCore 0.8.9, the inbuilt keyboard does not work. I tried using Roddy's boot ([here](https://github.com/acidanthera/bugtracker/issues/870#issuecomment-619118719)) and it works (as in, duet does not automatically detect OpenCore EFI so I manually have to select it everytime) but it breaks touchpad. 

Since that boot file has Ps2KeyboardDxe inbuilt, I had to disable OpenUsbKbDxe which broke support for my USB keyboard (but USB mouse works). 

Using [this](https://github.com/acidanthera/bugtracker/issues/870#issuecomment-619573830) driver did not help, either. In all the cases, I had KeySupport enabled and PS2MouseDxe as well.
